
export const map = {
    1 : { pressureMax:""},
    2 : { pressureMin:""},
    3 : { ppCalculado:""},
    4 : { weight:""},
    5 : { height:""},
    6 : { imc:""},
    7 : { waistCircumference:""},
    8 : { neckCircumference:""},
    9 : { hematocrit:""},
    10: { hemoglobin:""},
    11: { bloodGlucose:""},
    12: { glycosylatedHemoglobin:""},
    13: { totalCholesterol:""},
    14: { LDL:""},
    15: { HDL:""},
    16: { triglycerides:""},
    17: { sodium:""},
    18: { potassium:""},
    19: { uricAcid:""},
    20: { urea:""},
    21: { creatinine:""},
    22: { cKDEPI:""},
    23: { vitaminD:""},
    24: { mediaPAS24h:""},
    25: { mediaPAD24h:""},
    26: { mediaPASVigilia:""},
    27: { mediaPADVigilia:""},
    28: { mediaPASSono:""},
    29: { mediaPADSono:""},
    30: { descensoNoturnoPAS:""},
    31: { descensoNoturnoPAD:""},
    32: { mediaPAS:""},
    33: { mediaPAD:""},
    34: { massaVE:""},
    35: { indiceMassaVE:""},
    36: { medidaVESistole:""},
    37: { medidaVEDiastole:""},
    38: { medidaSeptoInterventricular:""},
    39: { medidaParedePosteriorVE:""},
    40: { medidaAtrioEsquerdo:""},
    41: { areaAtrioEsquerdo:""},
    42: { medidaAorta:""},
    43: { fraçãoEjeçãoVE:""},
    44: { pasPeriférica:""},
    45: { padPeriférica:""},
    46: { ppPeriférica:""},
    47: { pasCentral:""},
    48: { padCentral:""},
    49: { ppCentral:""},
    50: { augmentationIndex:""},
    51: { resistenciaVascular:""},
    52: { indiceCardiaco:""},
    53: { velocidadeOndaPulso:""},
    54: { duracaoTotalPeriodoEsforco:""},
    55: { totalMetAlcancado:""},
    56: { pasRepouso:""},
    57: { padRepouso:""},
    58: { pasPicoEsforco:""},
    59: { padPicoEsforco:""},
    60: { deltaPas:""},
    61: { deltaPad:""},
    62: { deltaPasMet:""},
    63: { deltaPadMet:""},
    64: { fcRepouso:""},
    65: { fcPicoEsforco:""},
    66: { fcPrimeiroMinutoRecuperacao:""},
    67: { indiceFuncaoCronotropica:""},
};


export const value = {
    pressureSistolica:"",
    pressureDiastolica:"",
    ppCalculado:"",
    weight:"",
    height:"",
    imc:"",
    waistCircumference:"",
    neckCircumference:"",
    hematocrit:"",
    hemoglobin:"",
    bloodGlucose:"",
    glycosylatedHemoglobin:"",
    totalCholesterol:"",
    LDL:"",
    HDL:"",
    triglycerides:"",
    sodium:"",
    potassium:"",
    uricAcid:"",
    urea:"",
    creatinine:"",
    ckdepi:"",
    vitaminD:"",
    mediaPas24h:"",
    mediaPad24h:"",
    mediaPasVigilia:"",
    mediaPadVigilia:"",
    mediaPasSono:"",
    mediaPadSono:"",
    descensoNoturnoPas:"",
    descensoNoturnoPad:"",
    mediaPas:"",
    mediaPad:"",
    massaVe:"",
    indiceMassaVe:"",
    medidaVeSistole:"",
    medidaVeDiastole:"",
    medidaSeptoInterventricular:"",
    medidaParedePosteriorVE:"",
    medidaAtrioEsquerdo:"",
    areaAtrioEsquerdo:"",
    medidaAorta:"",
    fracaoEjecaoVE:"",
    pasPeriferica:"",
    padPeriferica:"",
    ppPeriferica:"",
    pasCentral:"",
    padCentral:"",
    ppCentral:"",
    augmentationIndex:"",
    resistenciaVascular:"",
    indiceCardiaco:"",
    velocidadeOndaPulso:"",
    duracaoTotalPeriodoEsforco:"",
    totalMetAlcancado:"",
    pasRepouso:"",
    padRepouso:"",
    pasPicoEsforco:"",
    padPicoEsforco:"",
    deltaPas:"",
    deltaPad:"",
    deltaPasMet:"",
    deltaPadMet:"",
    fcRepouso:"",
    fcPicoEsforco:"",
    fcPrimeiroMinutoRecuperacao:"",
    indiceFuncaoCronotropica:"",
    datePressureMax: "",
    datePressureMin:"",
    datePPCalculado: "",
    dateHeartRate: "",
    dateAbdominalCircumference: "",
    dateNeck: "",
    dateWeight: "",
    dateHeight: "",
    dateImc: "",
    dateHematrocito: "",
    dateHemoglobina: "",
    dateGlicemia: "",
    dateHemoglobinaG: "",
    dateColesterolT: "",
    dateLDL: "",
    dateHDL: "",
    dateTriglicerideos: "",
    dateSodio: "",
    datePotassio: "",
    dateUrico: "",
    dateUreia: "",
    dateCreatinina: "",
    dateCKDEPI: "",
    dateVitaminaD: "",
    dateMediaPAS24h: "",
    dateMediaPAD24h: "",
    dateMediaPASVigilia: "",
    dateMediaPADVigilia: "",
    dateMediaPASSono: "",
    dateMediaPADSono: "",
    dateDescensoNoturnoPAS: "",
    dateDescensoNoturnoPAD: "",
    dateMediaPAS: "",
    dateMediaPAD: "",
    dateMassaVE: "",
    dateIndiceMassaVE: "",
    dateMedidaVESistole: "",
    dateMedidaVEDiastole: "",
    dateMedidaSeptoInterventricular: "",
    dateMedidaParedePosteriorVE: "",
    dateMedidaAtrioEsq: "",
    dateAreaAtrioEsq: "",
    dateMedidaAorta: "",
    dateFraçãoEjeçãoVE: "",
    datePASperiférica: "",
    datePADperiférica: "",
    datePPperiférica: "",
    datePAScentral: "",
    datePADcentral: "",
    datePPCentral: "",
    dateAugmentationIndex: "",
    dateResistenciaVascular: "",
    dateÍndiceCardiaco: "",
    dateVelocidadeOndaPulso: "",
    dateDuracaoTotalPeriodoEsforço: "",
    dateTotalMETAlcançado: "",
    datePASRepouso: "",
    datePADRepouso: "",
    datePASPicoEsforço: "",
    datePADPicoEsforço: "",
    dateDeltaPAD: "",
    dateDeltaPASMet: "",
    dateDeltaPADMet: "",
    dateFCRepouso: "",
    dateFCPicoEsforço: "",
    dateFCPrimeiroMinutoRe: "",
    dateErgometricoÍndiceCronotrópica: "",
    dateFunçãoCronotrópica: "",

};